### ISSUE TITLE
NotImplementedError running example in Augmented Analytic Kludge with 5PN trajectory

### ISSUE THREAD

**Issue by virtual-neutrino** [BlackHolePerturbationToolkit/FastEMRIWaveforms#10]
Running the example in the [documentation](https://bhptoolkit.org/FastEMRIWaveforms/html/tutorial/FastEMRIWaveforms_tutorial.html#Augmented-Analytic-Kludge-with-5PN-trajectory) for the Augmented Analytic Kludge with 5PN trajectory seems to throw a NotImplementedError.

For some reason the gpu_capability method is invoked from the GPUModuleBase class, in which it throws the NotImplementedError (while say in Pn5AAKWaveform, further down the road, it would return True). Given that changing this basic behavior in GPUModuleBase to say returning False here resolves the issue for me, I assume it is not a specific problem on my side (I'm working without gpu capability but the example has use_gpu set to False anyway so this shouldn't matter).

A better solution is probably to not generally do the sanity_check_gpu upon initializing GPUModuleBase, which also resolves the issue for me, but I'm perhaps not the best judge of this given that I don't know if this breaks anything else.

**Comment by mikekatz04** [comment]
Hello, which module actually running? If we look in the code here: 

https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/blob/f3c2d9834c5c677235cb8d1baf06cb6cf34df670/few/waveform.py#L970 

it has the gpu_capability = True for the Pn5AAKWaveform. I have run this recently on and off GPUs, so it has been okay. Can you send me more information?

**Comment by mikekatz04** [comment]
I am going to close this ticket for now as it seems this has not been a common issue. Please reopen this if it remains.
