### ISSUE TITLE
Web page bad link "examples notebook"

### ISSUE THREAD

**Issue by gabella** [BlackHolePerturbationToolkit/FastEMRIWaveforms#11]
Unsure where to put FastEMRIWaveforms web page bugs / issues, so there it is, the "example notebook" link on https://bhptoolkit.org/FastEMRIWaveforms/html/index.html which appears to point to https://bhptoolkit.org/FastEMRIWaveforms/html/examples/SchwarzschildEccentricWaveform_intro.ipynb pulls up a File Not Found error.

fyi, bill e.g.

**Comment by mikekatz04** [comment]
Thanks for this. I will correct this in the next update. It should just lead to https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/blob/master/examples/FastEMRIWaveforms_tutorial.ipynb
