### ISSUE TITLE
missing LPA.txt file in tutorial notebook

### ISSUE THREAD

**Issue by gabella** [BlackHolePerturbationToolkit/FastEMRIWaveforms#12]
Going through the tutorial notebook
https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/blob/master/examples/FastEMRIWaveforms_tutorial.ipynb
around cell 30 "Mode selection by noise-weighted power contribution" there is an attempt to read a file "files/LPA.txt" in the command
noise = np.genfromtxt("files/LPA.txt", names=True)
which does not exist and I cannot find it.  It seems to be a noise sensitivity datafile, maybe for LISA?

Any help is appreciated.  Thanks.

**Comment by mikekatz04** [comment]
Hi Bill, yes, it is a noise sensitivity file for LISA.I had not included it originally, but I will add it.
