### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by guilara** [BlackHolePerturbationToolkit/FastEMRIWaveforms#16]
Hi, very interesting package.

I've been trying to install it in our cluster but I'm running into compiling issues with cuda. (I'm new to it, so I'm not sure what's the problem): 

I've followed the install guide and used Anaconda.

And for cupy I have : cupy-cuda101              9.0.0                    pypi_0    pypi

 I get messages like this one :

include/cuda_complex.hpp(954): error: more than one instance of overloaded function "isnan" matches the argument list:
            function "isnan(double)"
            function "std::isnan(double)"
            argument types are: (double)
          detected during instantiation of "gcmplx::complex<_Tp> gcmplx::exp(const gcmplx::complex<_Tp> &) [with _Tp=double]" 
src/interpolate.cu(311): here

23 errors detected in the compilation of "/tmp/tmpxft_0000209b_00000000-12_interpolate.compute_75.cpp1.ii".
error: command '/opt/xxxx/compiler/cuda/10.1.243/bin/nvcc' failed with exit status 1

**Comment by mikekatz04** [comment]
Do you know what gcc the nvcc compiler uses?

**Comment by guilara** [comment]
Hi, I'm not sure. If its calling the default one it seems to be (from gcc --version) : gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
The one in the conda env seems to be: x86_64-conda-linux-gnu-gcc (crosstool-NG 1.24.0.133_b0863d8_dirty) 9.3.0

How can one make sure nvcc uses the latter?

**Comment by guilara** [comment]
This seems to have been the problem. Changed the compiler and now it compiles and seems to pass the tests. Thanks

**Comment by nielsw2** [comment]
Great. Glad to hear it is now working. Let us know if you find any other issues.
