### ISSUE TITLE
GSL bessel.c error for PN5 AAK model

### ISSUE THREAD

**Issue by znasipak** [BlackHolePerturbationToolkit/FastEMRIWaveforms#17]
I tried running the following snippet of code using a Jupyter notebook:

```
import few.waveform as waveform

M = 1e6
mu = 3e1
a = 0.99
p0 = 10.0
e0 = 0.02
Y0 = 0.7
Phi_phi0 = 0.0
Phi_theta0 = 0.0
Phi_r0 = 0.0

dt = 10.0
T = 4.0
qS = 0.2
phiS = 0.2
qK = 1.8
phiK = 1.8
dist = 1.0

inspiral_kwargs = {
   "DENSE_STEPPING": 0,
   "max_init_len": int(1e4),
 }
sum_kwargs = {
    "use_gpu": False, 
    "pad_output": False,
}

aak_waveform = waveform.Pn5AAKWaveform(inspiral_kwargs, sum_kwargs, use_gpu=False)
    
h = aak_waveform(M, mu, a, p0, e0, Y0, qS, phiS, qK, phiK, dist, Phi_phi0=Phi_phi0, Phi_theta0=Phi_theta0, Phi_r0=Phi_r0, mich=True, dt=dt, T=T)
```

It ended up crashing the kernel without any error message. I then ran it through python in the command line and got the following error message:

```
gsl: bessel.c:584: ERROR: error
Default GSL error handler invoked.
```

Similar issues have appeared when just trying to generate trajectories as well. I can provide other examples if needed.

**Comment by mikekatz04** [comment]
Thank you for bringing this up. I am looking into the issue.

**Comment by mikekatz04** [comment]
I believe I have isolated the issue. 

For the record: The issue is a gsl error within the conversion from Y to x_I at https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/blob/61988e5195acacd16927020edc4bd8dd1f03922d/src/FundamentalFrequencies.cc#L382. The function is accurate when compared to mathematical code when it does not throw an error. Therefore, it may be an inherent issue with the exact method for root finding used in the operation in this regime of inputs. Will discuss with @nielsw2 and try to find a solution. Inputs at lower spins should be fine.

**Comment by mikekatz04** [comment]
This is a new feature added in the most recent release.

**Comment by znasipak** [comment]
Thanks for looking into this. So it appears that I was using an older version of FEW (my previous git pull was from early April), and that release did not have the `Y_to_xI` function. So I pulled the most recent release and that did solve the GSL bessel.c error, but then I received GSL brent.c errors, beginning with spins of a = 0.65. I'm guessing has to do with the root-finding you mentioned above.  I meddled around with the solver myself, and reducing the search region seems to have fixed the issue for me.

In `Y_to_xI`, I made use of the fact that Y is usually close in value to xI and replaced 
```
x_lo = -0.999;
x_hi =  0.999;
```
with
```
x_lo = Y - 0.1;
x_hi = Y + 0.1;
	
x_lo = x_lo > -YLIM? x_lo : -YLIM;
x_hi = x_hi < YLIM? x_hi : YLIM;
```

This solves most of the `gsl: brent.c` errors I was receiving, but now the `gsl: bessel.c` error has returned. For example the parameters 

```
M = 5e5
mu = 3e1
a = 0.98
p0 = 10.0
e0 = 0.25
Y0 = 0.5
Phi_phi0 = 0.0
Phi_theta0 = 0.0
Phi_r0 = 0.0

dt = 10.0
T = 4.0
qS = 0.2
phiS = 0.2
qK = 1.8
phiK = 1.8
dist = 1.0
```
generated this error. I hope that this helps.

**Comment by mikekatz04** [comment]
There was a mistake in the last development merge. Please pull again and try with version 1.3.1. It has been updated with your suggestion for fixing the root finding. After updating that and running tests everything checks out. I can run the EMRI system you noted above without issue. If there is still an issue, what gsl version are you using?

**Comment by znasipak** [comment]
Yes this has removed the bessel.c error. Thanks!

**Comment by znasipak** [comment]
I got the `gsl: bessel.c:584: ERROR: error` once again. This time for the parameters
```
M = 5e5
mu = 10
a = 0.98
p0 = 10.1
e0 = 0.1
Y0 = 0.7
Phi_phi0 = 0.0
Phi_theta0 = 0.0
Phi_r0 = 0.0

dt = 10.0
T = 4.0
qS = 0.2
phiS = 0.2
qK = 1.8
phiK = 1.8
dist = 5.0
```

Again, this issue is appearing at high-spin, so this may be related to the poor behavior of the PN fluxes in this regime, as you mentioned on another issue.

**Comment by mikekatz04** [comment]
The issues seem always related to stepping over the separatrix. I found another spot where we should have been protecting against it. This seems especially unique to the PN fluxes at high spins. It should now be fixed again. Will close for now.
