### ISSUE TITLE
GPUassert: an illegal memory access was encountered when switching GPU with cupy.cuda.Device(num).use()

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#24]
When specifying a choice of GPU other than the default (0) on a system with multiple GPUs, a GPUassert is called and illegal memory access error is thrown on waveform generation. For Pn5AAK this occurs in `src/gpuAAK.cu`, for fast Schwarzchild this occurs in `src/interpolate.cu` or `src/matmul.cu`.  

To recreate add these two lines above some standard waveform generation code:
```
import cupy
cupy.cuda.Device(num).use()
```
where `num` is the index of a GPU other than 0.

**Comment by mikekatz04** [comment]
I think I know why this is. It is most likely that in the CUDA source code itself I do not provide a call to change the GPU. So cupy is probably choosing a different GPU while my CUDA source is not changing GPUs. I can probably add this functionality, but it will not be immediately.

**Comment by mikekatz04** [comment]
This is added. Coming in version 1.3.8. `from few.utils.utility import cuda_set_device`. 

It is a very thin wrapper for `from cupy.cuda.runtime.setDevice`
