### ISSUE TITLE
polarisation angle is incorrect if PhiS = PhiK

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#30]
Currently in `waveform.py` during the viewing angle calculation, if phiS = phiK then the polarization angle is directly input to be `0.5 np.pi/2` when in reality it should probably be `np.pi/2`, in line with `np.arctan2(np.inf)`.

**Comment by mikekatz04** [comment]
I have to look at this in more detail. The 0.5 may be due to the factor of 2 in np.cos(2.0 * psi_ldc).

**Comment by CChapmanbird** [comment]
I found this during looking at how to treat thetaS and thetaK going outside [0,pi] I was using this specific case, as these two parameters become degenerate at PhiS = PhiK. If one takes `theta_S -> 2 pi - theta_S` and `phi_S -> phi_S + pi`, the sky position vector is unchanged (and therefore, so should the polarization angle). Due to a numerical error, `sin(phi_S - phi_K) = sin(pi)` didn't come out to be exactly zero, and the polarization angle was being calculated to be pi / 2 from the `arctan2` call.

**Comment by CChapmanbird** [comment]
For this to be correct it would mean the polarization angle sharply drops by a factor of 2 as phiS - phiK approaches zero, which doesn't sound right.

**Comment by mikekatz04** [comment]
I think this sounds correct. Let's chat and we can add it in with the many small updates coming up.

**Comment by mikekatz04** [comment]
You were right. I looked at other codes. Both factors got added when converting c code to python. This has been fixed in pull request #33 .
