### ISSUE TITLE
AAK trajectory does not reach separatrix in particular case

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#31]
I have run into a set of parameters that produce some strange behaviour with the AAK. 

Minimal working example:

```
import time
import numpy as np
import matplotlib.pyplot as plt
from few.waveform import GenerateEMRIWaveform
from few.utils.utility import get_p_at_t, get_mu_at_t

use_gpu = True
kerr = GenerateEMRIWaveform(
    "Pn5AAKWaveform",
    sum_kwargs=dict(pad_output=True),
    use_gpu=use_gpu,
    return_list=True, inspiral_kwargs={'max_init_len':int(1e8)}
)

# set initial parameters
M = 1e6
a = 0.9354
p0 = 18
e0 = 0.62   # Behaves very strangely above ~ 0.5459,
Y0 = 0.6334583
T = 2.0
Phi_phi0 = 1.0
Phi_theta0 = 2.0
Phi_r0 = 3.0
qS = 0.214432
phiS = 0.3245324
qK = 0.24324523
phiK = 0.432432
dl = 1.3223
mu_new = 1.5874

p0 = 4.1   

injection_params = np.array(
    [
        M,  # MBH Mass  0
        mu_new,  # CO Mass   1
        a,  # will ignore  (if not kerr) # MBH Spin     2
        p0,  # Semi-latus rectum of orbit       3
        e0,  # Initial eccentricity     4
        Y0,  # will ignore (if not kerr)   # cosine of the inclination angle        5
        dl,  # distance to the source     6
        qS,  # polar viewing angle (eclip.)     7
        phiS,  # azimuthal viewing angle (eclip.)        8
        # Spin angles....
        qK,  # polar spin angle        9
        phiK,  # polar azimuthal spin angle      10
        Phi_phi0,  #    11
        Phi_theta0,  #  12
        Phi_r0,  #    13
    ]
)
waveform_kwargs = {"T": T, "dt": 15}
wave = kerr(*injection_params, **waveform_kwargs)
plt.plot(wave[0].get())
plt.show()
```

If `e0 < 0.546` the waveform reaches the separatrix early, and stops. At `e0 = 0.546` however the waveform generation returns `gsl: ellint.c:505: ERROR: domain error`. At values higher than this for e0, e.g. `e0 > 0.55, the waveform returns but is clearly incorrect (it never plunges and amplitude gets very small).

I checked the trajectory and it never reaches within 0.1 of the separatrix past this error point:
![image](https://user-images.githubusercontent.com/47143521/125290917-bc220b00-e318-11eb-9b96-90b693a7f1ed.png)
so it seems the stopping condition isn't reached and the integrator skips over the separatrix and continues into a (presumably) unphysical trajectory.

I don't know for what kinds of parameters this will occur for, but it's probably to do with high eccentricities + spins leading to low separatrix values that are more sensitive to larger integrator steps.

**Comment by CChapmanbird** [comment]
I re-ran with dense stepping and found that the above behaviour was replicated:
![image](https://user-images.githubusercontent.com/47143521/125294481-356f2d00-e31c-11eb-9aaa-0491524bd73a.png)
This isn't an integrator issue. It could be a limitation of the AAK, as these trajectories are clearly unphysical.

**Comment by CChapmanbird** [comment]
That being said, I ran dense stepping again but with a larger value of `p0`:
![image](https://user-images.githubusercontent.com/47143521/125295910-a4995100-e31d-11eb-982c-086a59d0e06e.png)
Clearly the above behaviour isn't reached in this case. I'm not sure why this would happen for dense stepping where we are using a constant time-step in the trajectory.

**Comment by alvincjk** [comment]
Hi Christian - assuming there are no bugs in the integrator, what you're seeing is probably the result of pushing PN calculations into a regime where they're not supposed to be used. These expansions are in both PN and eccentricity, so they can't really be trusted for e>0.5 anywhere along the inspiral, much less this close to plunge (where they presumably start getting pathological, as you found). If you really need to look at this regime right now, I would suggest switching to the Gair-Glampedakis fluxes, which have their own set of problems but should at least be void of such qualitative pathologies.

**Comment by CChapmanbird** [comment]
Hi Alvin, I think you're right that this is a symptom of PN formulas converging poorly for these conditions. It's quite clear that waveforms producing this behaviour aren't particularly useful so it could be sensible to offer a Schwarzchild separatrix to truncate the waveform early. I have made a separate issue #32 for this suggestion, so it makes sense to close this one.
