### ISSUE TITLE
Optional Schwarzchild plunge condition for AAK

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#32]
As the accuracy of the AAK trajectory is diminished significantly for high spin prograde orbits, it could be useful to be able to set the Schwarzchild separatrix 6 + 2e to truncate the waveform early. While likely to underestimate the SNR of the waveform the results will be much more consistent.

This would only need to be coded in for prograde orbits, as for retrograde orbits the Kerr separatrix is larger than the Schwarzchild one and should be used instead (if I understand correctly).

**Comment by mikekatz04** [comment]
This capability was added in pull request #33. Thank you for the suggestion!
