### ISSUE TITLE
If xI < 0 then the Kerr separatrix will be larger than the Schwarzchild one and the integrator will walk past the Kerr separatrix when `enforce_schwarz_sep` is set to True

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#35]
May need to watch out here, as if xI < 0 then the Kerr separatrix will be larger than the Schwarzchild one and the integrator will walk past the Kerr separatrix.

_Originally posted by @CChapmanbird in https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/pull/33#r691435494_

**Comment by mikekatz04** [comment]
Fixed. If xI < 0, then `enforce_schwarz_sep` is forced to False.
