### ISSUE TITLE
`SystemError: EllipticE failed with argument k: -nan / Error code: 11`

### ISSUE THREAD

**Issue by cchapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#41]
I'm running into failure in waveform generation for an innocuous set of parameters:

`
M=4.23133601e+06 
mu=1.29621020e+00 
a=8.02435980e-01 
p0=4.46180186e+00
e=1.61923468e-01 
Y0=9.36172586e-01 
d= 5.00000000e-01 
qS=2.26989260e+00
thetaS=5.53008468e+00 
qK=2.85000760e+00 
thetaK=0.00000000e+00 
phi_r0=0.00000000e+00
phi_theta0=0.00000000e+00 
phi_phi0=0.00000000e+00
`
Other times I've had errors, the error has `k > 1` which I assume is out of bounds. This is a `nan` however, which is quite different. Where could the `nan` be coming from?

**Comment by mikekatz04** [comment]
Can you put up the code that reproduces this? When I quickly run those parameters, it is fine.

**Comment by mikekatz04** [comment]
I did that, still no error.
