### ISSUE TITLE
get_separatrix dimensionality check

### ISSUE THREAD

**Issue by mrizzo25** [BlackHolePerturbationToolkit/FastEMRIWaveforms#48]
make sure all inputs of get_separatrix have the same dimensions

**Comment by mikekatz04** [comment]
I told Monica to put this here to remind me. I believe right now it checks if the spin is scalar and then scales it to the other parameters if needed. But I think we need to check and make sure all of the inputs have the same dimension.

**Comment by mikekatz04** [comment]
I fixed this.
