### ISSUE TITLE
`err` keyword argument for trajectory module is unused/unimplemented for `func="pn5"`

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#49]
For a trajectory `traj = EMRIInspiral(func="pn5")`, the keyword argument `err` (which should control the accuracy of the integrator) does nothing.

**Comment by CChapmanbird** [comment]
This seems like it's a general issue for all choices of inspiral function. Instead of `err` the GSL evolve is set to `1e-10`.

**Comment by mikekatz04** [comment]
This has been fixed in the new version.
