### ISSUE TITLE
Circular trajectory gets cut-off before ISCO

### ISSUE THREAD

**Issue by znasipak** [BlackHolePerturbationToolkit/FastEMRIWaveforms#50]
I tried to generate trajectory data for a circular inspiral. The code can be found below.
```
import numpy as np
from few.trajectory.inspiral import EMRIInspiral
traj = EMRIInspiral(func="SchwarzEccFlux")

M = 1e6
mu = 10
p0 = 10.0
e0 = 0.0

t, p, e, x, Phi_phi, Phi_theta, Phi_r = traj(M, mu, 0., p0, e0, 1.0, in_coordinate_time=False)
```

Calling `p[-1]` returns `8.382259221444595` instead of `6` as expected.

**Comment by CChapmanbird** [comment]
The trajectory module has a keyword argument `T` which defines the (maximum) duration for the inspiral trajectory in years, and it has a default value of `1`. Your inspiral plunges for `T > 1`, so it is truncated. To obtain a full inspiral you can either raise `T` to some fiducial maximum value (e.g. `10`) or use the `get_at_t` utility functions to adjust `p0` or `mu` such that the inspiral plunges for `T=1`.
