### ISSUE TITLE
AAK waveform generation unpredictably fails in FEW `1.4.6`

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#53]
As of this update errors are produced on AAK waveform generation. The following reproduces this issue for me:
```
from few.waveform import GenerateEMRIWaveform
wform = GenerateEMRIWaveform("Pn5AAKWaveform",use_gpu=True)
wform(1e5, 1e1, 0.2, 12.0, 0.4, 0.8, 1., 0.2, 0.4, 0.25, 0.45, 0., 0., 0., dt=15., T=2) # works fine
wform(1e5, 1e1, 0.2, 15.0, 0.4, 0.8, 1., 0.2, 0.4, 0.25, 0.45, 0., 0., 0., dt=15., T=2) # either GPUAssert or Segmentation fault
```

**Comment by lorenzsp** [comment]
Hi Christian, I should have solved this problem. The integrator was checking not to have passed the separatrix. However, the separatrix calculation is based on x and this quantity was obtained with a conversion from Y. This conversion is based on a root finder which involves values of p which were already smaller than the separatrix and sometimes also negative. This was leading to unpredictable failures depending on the adaptive steps of the integrator. I have added a sanity check in the integrator. You can find the fixed code in the [fix](https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/tree/fix) branch. Let me know if I actually solved the issue.

**Comment by CChapmanbird** [comment]
Hey Lorenzo,

Thanks for checking this out. I can't test the code right now but I suspect this will not solve the issue, because the error message was dependent on whether the waveform was being generated on GPU or CPU, whereas the trajectory code is always called on the CPU. It is possible the issue you found causes further problems down the line (in gpuAAK.cu) but I would not be surprised if there is something else. Cheers

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mikekatz04** [comment]
This waveform runs fine for me now. If the issue persists, please reopen it.
