### ISSUE TITLE
About the number of data points

### ISSUE THREAD

**Issue by ljq2088** [BlackHolePerturbationToolkit/FastEMRIWaveforms#67]
May I ask a naive question as a beginner: I used function "few" and "GenerateEMRIWaveform" to generate waveform, and found that the number of data is not equal to T/dt, and I wonder the the number of data points depends on which parameters.

**Comment by mikekatz04** [comment]
Hello, take a look at the tutorial. If you are not padding the output, it will just make the waveforms as long as it needs to be. You can add `"pad_output": True,` to the summation kwargs.
