### ISSUE TITLE
A typo in FEW example

### ISSUE THREAD

**Issue by mx-Liu123** [BlackHolePerturbationToolkit/FastEMRIWaveforms#70]
Hi, there is a typo in https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/blob/master/examples/FastEMRIWaveforms_tutorial.ipynb:

![image](https://user-images.githubusercontent.com/53643137/229096205-86a8e5f1-026a-4532-abd4-9c928928986b.png)

The order of parameters is wrong. For above setting, chaging dist doesn't change the SNR. The "dist" should be placed between Y0 and qS:

![image](https://user-images.githubusercontent.com/53643137/229096342-a6145583-0519-4bda-95e5-a9b110d0e931.png)

**Comment by mikekatz04** [comment]
Thank you for finding this!! It is fixed now.
