### ISSUE TITLE
Why are there two types of code of EMRIs' GW

### ISSUE THREAD

**Issue by ChenYigu2021** [BlackHolePerturbationToolkit/FastEMRIWaveforms#71]
I am a naive to learn Teukolsky perturbation theory and use FastEMRIWaveforms code. Here's a question that bothers me. 
Why are there two types of code of EMRIs' GW, some are solve the general trajectory and flux in SWBH spacetime, and others are solve the circulartrajectory of on the equator in Kerr BH spacetime.

**Comment by mikekatz04** [comment]
The various equations for EMRIs are easier or harder to solve in certain limits and result in easier or harder waveforms to build. Over time we will build up to the full generic case, but the theory nor the waveform creation are there yet. On Apr 23, 2023, at 11:00 PM, ChenYigu2021 ***@***.***> wrote:﻿
I am a naive to learn Teukolsky perturbation theory and use FastEMRIWaveforms code. Here's a question that bothers me.
Why are there two types of code of EMRIs' GW, some are solve the general trajectory and flux in SWBH spacetime, and others are solve the circulartrajectory of on the equator in Kerr BH spacetime.

**Comment by ChenYigu2021** [comment]
> 

Looking forward to the emergence of a geneic and convenient code.
