### ISSUE TITLE
Zenodo Files Download Failed

### ISSUE THREAD

**Issue by asantini29** [BlackHolePerturbationToolkit/FastEMRIWaveforms#86]
The new version of FEW is not able to download the files from Zenodo anymore. By checking out at this commit `cf1a3f211577b203a272871ab4c6c5fd19071ab4` it is possible to obtain a working version on M2

**Comment by mikekatz04** [comment]
I think they are still working for me. Can you post the error or some output that would give me a bit more detail?

I am going to close this for now, assuming it is okay, but we can reopen it if needed.

**Comment by asantini29** [comment]
Hi Michael,

I'll try again to install the latest version and I'll let you know if I
still get any error.

Alessandro

Il gio 7 dic 2023, 19:21 Michael Katz ***@***.***> ha scritto:
