### ISSUE TITLE
python setup.py install fails

### ISSUE THREAD

**Issue by gabella** [BlackHolePerturbationToolkit/FastEMRIWaveforms#9]
Sorry if this shows up somewhere else, if so would you please point me there.

After setting up the few_env environment and activating it, when I git clone and then run
python setup.py install
I see many warnings but it fails with a gcc error, seems to be calling the system GCC and not the few_env one:

include/cuda_complex.hpp: In function ‘gcmplx::complex<_Tp> gcmplx::acosh(const gcmplx::complex<_Tp>&)’:
include/cuda_complex.hpp:1028:12: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
         if (std::isinf(__x.imag()))
            ^
g++ -pthread -shared -B /home/gabellwe/anaconda3/envs/few_env/compiler_compat -L/home/gabellwe/anaconda3/envs/few_env/lib -Wl,-rpath=/home/gabellwe/anaconda3/envs/few_env/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/matmul.o build/temp.linux-x86_64-3.7/src/pymatmul_cpu.o -lgsl -lgslcblas -llapack -llapacke -lgomp -lhdf5 -lhdf5_hl -o build/lib.linux-x86_64-3.7/pymatmul_cpu.cpython-37m-x86_64-linux-gnu.so
building 'pyFLUX' extension
gcc -pthread -B /home/gabellwe/anaconda3/envs/few_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gabellwe/anaconda3/envs/few_env/lib/python3.7/site-packages/numpy/core/include -Iinclude -I/home/gabellwe/anaconda3/envs/few_env/include/python3.7m -c src/Interpolant.cc -o build/temp.linux-x86_64-3.7/src/Interpolant.o -std=c++11 -fopenmp -fPIC -D__USE_OMP__
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from src/Interpolant.cc:19:0:
include/Interpolant.h:22:30: fatal error: gsl/gsl_interp2d.h: No such file or directory
 #include <gsl/gsl_interp2d.h>
                              ^
compilation terminated.
error: command 'gcc' failed with exit status 1

thanks for any help, bill e.g.

**Comment by mikekatz04** [comment]
Hi Bill, thanks you for interest in FEW!

This error occurs when using older versions of gsl, I think gsl < 2.0. But since you are using the conda environment, this means it is not finding the conda installed gsl because it is compiled with the wrong compiler as you point out. 

Is this on linux I assume? Someone else had a similar issue that was not put on github and it was effectively a deep symbolic link that prevented python setupy.py install from accessing the conda installed compiler. So, my recommendation is to try to reinstall from scratch and verify that the compiler from the conda env is being used (this is the gcc_linux-64 & gxx_linux-64 in the env setup). If it is using the wrong compiler, it is most likely some issue specific to your device in terms of a symlink that prevents the usage or something like that. It is a bit harder for me to help with specifics if that is the issue. If you can run 'conda list' in your environment and post it here, that would be helpful. 

Please let me know if this works. 

Michael

**Comment by gabella** [comment]
Michael,
  Thanks for your response.  So I did remove Anaconda3 by deleting the directory.  I logged out and in, to reset my PATH...just in case.  I re-installed Anaconda3.  I skipped the step "conda init" to keep it out of my .tcshrc / .bashrc files.  I sourced and activated in the the conda base environment.  Then I installed the few_env .  Last time I did the install from my none conda environment.
  That looks nominal w.r.t. gcc and gxx, from the output:
    freetype-2.10.4            |       h0708190_1         890 KB  conda-forge
    gcc_impl_linux-64-9.3.0    |      h70c0ae5_18        43.1 MB  conda-forge
    gcc_linux-64-9.3.0         |      hf25ea35_30          23 KB  conda-forge
    gettext-0.19.8.1           |    h0b5b191_1005         3.6 MB  conda-forge
...
    gstreamer-1.18.4           |       h76c114f_0         2.0 MB  conda-forge
    gxx_impl_linux-64-9.3.0    |      hd87eabc_18        10.7 MB  conda-forge
    gxx_linux-64-9.3.0         |      h3fbe746_30          23 KB  conda-forge
    h5py-3.1.0                 |nompi_py37h1e651dc_100         1.2 MB  conda-forge
...
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  gcc_impl_linux-64  conda-forge/linux-64::gcc_impl_linux-64-9.3.0-h70c0ae5_18
  gcc_linux-64       conda-forge/linux-64::gcc_linux-64-9.3.0-hf25ea35_30
...
  gstreamer          conda-forge/linux-64::gstreamer-1.18.4-h76c114f_0
  gxx_impl_linux-64  conda-forge/linux-64::gxx_impl_linux-64-9.3.0-hd87eabc_18
  gxx_linux-64       conda-forge/linux-64::gxx_linux-64-9.3.0-h3fbe746_30
  h5py               conda-forge/linux-64::h5py-3.1.0-nompi_py37h1e651dc_100
...
gettext-0.19.8.1     | 3.6 MB    | ######################################################### | 100% 
gxx_linux-64-9.3.0   | 23 KB     | ######################################################### | 100% 
libcblas-3.9.0       | 11 KB     | ######################################################### | 100% 
...  
cryptography-3.4.6   | 1.1 MB    | ######################################################### | 100% 
cycler-0.10.0        | 9 KB      | ######################################################### | 100% 
gcc_linux-64-9.3.0   | 23 KB     | ######################################################### | 100% 
pycparser-2.20       | 94 KB     | ######################################################### | 100% 

But when I am done, and activate the environment, and look where gcc and g++ are they are both in /usr/bin, the system versions.
So I look for them in the few_env path, 
find ~/anaconda3/envs/few_env/ -name gcc\*
I see many entries for it, but NONE are in ~/anaconda3/envs/few_env/bin  and that is the only pre-pended path to my usual PATH.  Should I add the link by hand?  There is a "gcc" in ~/anaconda3/envs/few_env/libexec/gcc/x86_64-conda-linux-gnu/9.3.0/ .
Looking for  g++ when I do "find ~/anaconda3/envs/few_env/ -name g++\*" , see files starting with g++ but none that are g++ itself.
"find ~/anaconda3/envs/few_env/ -name gxx\*"  shows only two JSON files.

Seems like I want to put in the links  g++ -> gcc and gcc -> gcc in the few_env/bin folder.

I will try this on different computers and see how the install goes.  I am working on a Cent-OS 7.9 system, recently updated, 
uname -a
Linux walle.csb-phy.vanderbilt.edu 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

Thanks for any help and sorry about the verbosity of my post:)  bill e.g.

**Comment by mikekatz04** [comment]
Hi Bill, no problem at all! Yea, it seems like a sym-linking issue. When I run setup.py install on the computing cluster (linux), the compiler is shown as `/home/mlk667/.conda/envs/few_env/bin/x86_64-conda-linux-gnu-c++` and `/home/mlk667/.conda/envs/few_env/bin/x86_64-conda-linux-gnu-cc`.

**Comment by gabella** [comment]
Could you tell me which version of Anaconda3 or conda you are running?
I am using their latest and greatest: Anaconda3-2020.11-Linux-x86_64.sh
and
conda --version
conda 4.9.2

**Comment by gabella** [comment]
Just tried one version earlier of the Anaconda3-2020.07-Linux-x86_64.sh and see the system gcc being called on our Centos-7.9.
Tried the most recent Anaconda3-2020.11-Linux-x86_64.sh on my laptop Fedora 33 system and also using the system gcc.  They both call gcc with the -B switch for finding the Conda "ld" command instead of the system one.  Like in the Centos system, from python setup.py install...
gcc -pthread -B /home/gabellwe/anaconda3/envs/few_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gabellwe/anaconda3/envs/few_env/lib/python3.7/site-packages/numpy/core/include -Iinclude -I/home/gabellwe/anaconda3/envs/few_env/include/python3.7m -c src/Interpolant.cc -o build/temp.linux-x86_64-3.7/src/Interpolant.o -std=c++11 -fopenmp -fPIC -D__USE_OMP__
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from src/Interpolant.cc:19:0:
include/Interpolant.h:22:30: fatal error: gsl/gsl_interp2d.h: No such file or directory
 #include <gsl/gsl_interp2d.h>
                              ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by mikekatz04** [comment]
That is weird. Can you send me the output from `conda list`?

**Comment by gabella** [comment]
I think I found it.  Was careful to uninstall all my Anaconda3 and Miniconda3 experiments and re-installed Anaconda3.
I think the important part was to be in bash for the "python setup.py install" .  Lots of warnings, but no errors and looks successful, still testing.

One of the last gcc calls I show below:

...
/home/gabellwe/anaconda3/envs/few_env/bin/x86_64-conda-linux-gnu-c++ -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/gabellwe/anaconda3/envs/few_env/lib
...
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing few-1.2.2-py3.7-linux-x86_64.egg
creating /home/gabellwe/anaconda3/envs/few_env/lib/python3.7/site-packages/few-1.2.2-py3.7-linux-x86_64.egg
Extracting few-1.2.2-py3.7-linux-x86_64.egg to /home/gabellwe/anaconda3/envs/few_env/lib/python3.7/site-packages
Adding few 1.2.2 to easy-install.pth file

Installed /home/gabellwe/anaconda3/envs/few_env/lib/python3.7/site-packages/few-1.2.2-py3.7-linux-x86_64.egg
Processing dependencies for few==1.2.2
Finished processing dependencies for few==1.2.2

**Comment by mikekatz04** [comment]
Got it. I am glad you figured out the issue. Yea, when this happens, it is usually something weird like that. I am going to close this issue.
