### ISSUE TITLE
Missing source files for cpu installation

### ISSUE THREAD

**Issue by gyy0592** [BlackHolePerturbationToolkit/FastEMRIWaveforms#94]
I am trying to install the fastEMRIWaveforms from the source code.
The nvcc compilation is fine, but the problem is on the gcc part.
In the setup.py I found
```python
matmul_cpu_ext = Extension(
    "pymatmul_cpu", sources=["src/matmul.cpp", "src/pymatmul_cpu.pyx"], **cpu_extension
    # "pymatmul_cpu", sources=["src/pymatmul.cpp", "src/pymatmul.pyx"], **cpu_extension
)

interp_cpu_ext = Extension(
    "pyinterp_cpu",
    sources=["src/Utility.cc", "src/interpolate.cpp", "src/pyinterp_cpu.pyx"],
    **cpu_extension,
)

AAK_cpu_ext = Extension(
    "pycpuAAK",
    sources=["src/Utility.cc", "src/gpuAAK.cpp", "src/gpuAAKWrap_cpu.pyx"],
    **cpu_extension,
)
```

The problem is that there are no CPU files for this installation, for example **src/pymatmul_cpu.pyx** is not found, at least not under the master branch. 

However, I commented the cpu_extension part to finish the installation, not sure whether they're essentialor not.

**Comment by hoyc1** [comment]
I also ran into this issue. I found that if I reverted `setup.py` from master to the version in e4038dacd99fa07a545af593beeb88d882e92fd2, I no longer experienced this problem. I suspect that making this package `pip` installable has affected installation from source for the latest commits.

**Comment by AminBoumerdassi** [comment]
Earlier in the code, the script copies the .pyx scripts to their cpu variants from line 379:

`# Install cpu versions of gpu modules

# need to copy cuda files to cpp for this special compiler we are using
# also copy pyx files to cpu version
src = "src/"

cp_cu_files = ["matmul", "interpolate", "gpuAAK"]
cp_pyx_files = ["pymatmul", "pyinterp", "gpuAAKWrap"]

for fp in cp_cu_files:
    shutil.copy(src + fp + ".cu", src + fp + ".cpp")

for fp in cp_pyx_files:
    shutil.copy(src + fp + ".pyx", src + fp + "_cpu.pyx")
`

Previous versions of FEW also do the same thing, yet the repo doesn't contain these _cpu.pyx files. My guess is that these files are created temporarily but for some reason this doesn't work in the most recent version of FEW.

I'm guessing a rollback to V1.4.4 would be a possible workaround for the time being.

**Comment by mikekatz04** [comment]
Hi all, sorry about this. In switching to a pip installable setup, I forgot to update instructions for installing from source. You 'run python scripts/prebuild.py'. This copies the files like it used to all in the same script. I need to go through and fix this when I get some time.

**Comment by iphysresearch** [comment]
> Hi all, if this helps anyone: I needed to copy the 'scripts/prebuild.py' to its parent folder and run it. Also, I needed to install :
> 
> ```shell
> conda install libxcrypt libxcrypt1
> ```

Thx! It works for me!
However, I got the following error when I try to test `use_gpu=True`:

```python
(lisa_env) root@b2e7cb42baad:/home/main/FastEMRIWaveforms# python
Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from few.waveform import GenerateEMRIWaveform
>>> gen_wave = GenerateEMRIWaveform("FastSchwarzschildEccentricFlux", use_gpu=False)
>>> gen_wave = GenerateEMRIWaveform("FastSchwarzschildEccentricFlux", use_gpu=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/main/FastEMRIWaveforms/few/waveform.py", line 87, in __init__
    self.waveform_generator = waveform(*args, **kwargs)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/main/FastEMRIWaveforms/few/waveform.py", line 845, in __init__
    SchwarzschildEccentricWaveformBase.__init__(
  File "/home/main/FastEMRIWaveforms/few/waveform.py", line 446, in __init__
    self.amplitude_generator = amplitude_module(**amplitude_kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/main/FastEMRIWaveforms/few/amplitude/romannet.py", line 148, in __init__
    self.neural_layer = neural_layer_wrap
                        ^^^^^^^^^^^^^^^^^
NameError: name 'neural_layer_wrap' is not defined. Did you mean: 'neural_layer_wrap_cpu'?
```

**Comment by smmasruk** [comment]
Just to be sure can you run everything in '''shell
few_env
'''

**Comment by mikekatz04** [comment]
If the it is not finding pymatmul, it means the install cannot find the CUDA information. I am going to close this for now as this should be fixed in the most recent versions. Reopen if you need to.
